version: "3"
services:
  backend:
    build: .
    container_name: backend
    ports:
      - 5000:5000
    depends_on:
      - postgres
    environment:
      REDIS_URI: redis://redis:6379
      POSTGRES_URL: postgres:5432
      POSTGRES_USER: octorock
      POSTGRES_DB: nonmatch
      POSTGRES_PASSWORD: postgres
      TMC_REPO: /opt/tmc
    volumes:
      - .:/opt/backend
      - ../tmc:/opt/tmc
  
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: octorock
      POSTGRES_DB: nonmatch
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../backup:/opt/backup

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
