"""Add compile flags

Revision ID: 244b528b3b93
Revises: 5be23b566654
Create Date: 2022-07-14 18:35:20.361099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244b528b3b93'
down_revision = '5be23b566654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('function', sa.Column('compile_flags', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('function', 'compile_flags')
    # ### end Alembic commands ###
