"""Add is_deleted for submissions

Revision ID: 43439ad5fe5d
Revises: 89be1eead1be
Create Date: 2022-08-21 12:53:00.428025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43439ad5fe5d'
down_revision = '89be1eead1be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'is_deleted')
    # ### end Alembic commands ###
