"""Add decomp.me fields

Revision ID: 4fae69f9be6e
Revises: f4fd2ec14bec
Create Date: 2022-03-21 10:18:22.449340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fae69f9be6e'
down_revision = 'f4fd2ec14bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('function', sa.Column('decomp_me_scratch', sa.String(length=10), nullable=True))
    op.add_column('function', sa.Column('decomp_me_matched', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('function', 'decomp_me_matched')
    op.drop_column('function', 'decomp_me_scratch')
    # ### end Alembic commands ###
