"""Add comments to submission

Revision ID: 5be23b566654
Revises: 4fae69f9be6e
Create Date: 2022-07-11 18:40:00.990723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be23b566654'
down_revision = '4fae69f9be6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('comments', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'comments')
    # ### end Alembic commands ###
