"""Add compiled field

Revision ID: 8716917910ab
Revises: 1a90a1e3749b
Create Date: 2022-01-03 19:52:39.880626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8716917910ab'
down_revision = '1a90a1e3749b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('compiled', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'compiled')
    # ### end Alembic commands ###
