"""File does not have to be unique

Revision ID: b22b63d2637e
Revises: 7b10a01330fa
Create Date: 2021-12-31 12:30:24.160369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b22b63d2637e'
down_revision = '7b10a01330fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('function_file_key', 'function', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('function_file_key', 'function', ['file'])
    # ### end Alembic commands ###
