"""empty message

Revision ID: b84bb0dc5139
Revises: 8185d6b80a40
Create Date: 2022-01-07 20:07:05.005743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84bb0dc5139'
down_revision = '8185d6b80a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('function', sa.Column('is_submitted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('pr', sa.Column('url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pr', 'url')
    op.drop_column('function', 'is_submitted')
    # ### end Alembic commands ###
