"""Add flag to show that code has a equivalent try

Revision ID: ba000f8233cc
Revises: 43439ad5fe5d
Create Date: 2022-08-21 15:27:45.425121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba000f8233cc'
down_revision = '43439ad5fe5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('function', sa.Column('has_equivalent_try', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('function', 'has_equivalent_try')
    # ### end Alembic commands ###
