"""Add fakeness score

Revision ID: eaa873a8781c
Revises: f49ce67c9e3e
Create Date: 2023-12-22 13:55:21.166002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaa873a8781c'
down_revision = 'f49ce67c9e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('function', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_fakematch', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('best_fakeness_score', sa.Integer(), server_default=sa.text('99999'), nullable=True))

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fakeness_score', sa.Integer(), server_default=sa.text('-1'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('fakeness_score')

    with op.batch_alter_table('function', schema=None) as batch_op:
        batch_op.drop_column('best_fakeness_score')
        batch_op.drop_column('is_fakematch')

    # ### end Alembic commands ###
