"""Add function addr

Revision ID: f179a0c43d80
Revises: 88171f4ed7d9
Create Date: 2022-01-19 13:00:32.714661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f179a0c43d80'
down_revision = '88171f4ed7d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('function', sa.Column('addr', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('function', 'addr')
    # ### end Alembic commands ###
