"""Add status to pr

Revision ID: f49ce67c9e3e
Revises: ba000f8233cc
Create Date: 2022-09-13 11:25:29.886352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49ce67c9e3e'
down_revision = 'ba000f8233cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pr', sa.Column('is_submitted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('pr', sa.Column('is_error', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('pr', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('pr', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    op.execute('UPDATE "pr" SET is_submitted=true WHERE url is not null')
    op.execute('UPDATE "pr" SET is_error=true, error=\'unknown error\' WHERE url is null')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pr', 'error')
    op.drop_column('pr', 'is_error')
    op.drop_column('pr', 'is_submitted')
    op.drop_column('pr', 'time_updated')
    # ### end Alembic commands ###
