"""Add flag to show that code has a try with code

Revision ID: f4fd2ec14bec
Revises: f179a0c43d80
Create Date: 2022-02-15 11:40:51.074553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4fd2ec14bec'
down_revision = 'f179a0c43d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('function', sa.Column('has_code_try', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###
    op.execute('UPDATE "function" SET has_code_try=true WHERE is_asm_func = false')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('function', 'has_code_try')
    # ### end Alembic commands ###
